## Handling Categorical columns

In [1]:
### autoreloader
%load_ext autoreload
%autoreload 2

In [2]:
### setting up the system path
import sys
sys.path.append('../')

In [3]:
### importing the functions from src files
from src.data.load_data import load_data, get_unique, get_nan, get_shape, get_value_counts, get_info, drop_col, save_data
from src.processing.process_categorical import one_hot, label_encode, cat_summary

In [4]:
### setting up the data path
cat_cols_train_path = '../data/split_features/cat_cols_train.csv'
cat_cols_valid_path = '../data/split_features/cat_cols_valid.csv'

##### *************** Train data *****************

In [31]:
### loading the data
cat_cols_train = load_data(cat_cols_train_path)
cat_cols_train.head()

,Transaction_Type,Device_Type,Location,Merchant_Category,Card_Type,Authentication_Method
0,ATM Withdrawal,Tablet,London,Travel,Mastercard,PIN
1,Bank Transfer,Mobile,New York,Electronics,Visa,OTP
2,ATM Withdrawal,Tablet,Sydney,Electronics,Mastercard,OTP
3,Online,Mobile,London,Travel,Discover,PIN
4,Online,Mobile,Sydney,Groceries,Amex,Password

In [6]:
### checking the shape
get_shape(cat_cols_train)

(40000, 6)

In [7]:
### checking the nan values
get_nan(cat_cols_train)

Transaction_Type         0
Device_Type              0
Location                 0
Merchant_Category        0
Card_Type                0
Authentication_Method    0
dtype: int64

In [8]:
### all the features needs the one hot encoding
### there is no label based categorical feature

In [9]:
### checking the summary of the columns
cat_summary(cat_cols_train)

{'Transaction_Type': {'n_unqiue': 4,
  'value_counts': Transaction_Type
  POS               10132
  Online            10030
  ATM Withdrawal     9921
  Bank Transfer      9917
  Name: count, dtype: int64},
 'Device_Type': {'n_unqiue': 3,
  'value_counts': Device_Type
  Tablet    13404
  Mobile    13340
  Laptop    13256
  Name: count, dtype: int64},
 'Location': {'n_unqiue': 5,
  'value_counts': Location
  Tokyo       8153
  Mumbai      7978
  Sydney      7965
  New York    7958
  London      7946
  Name: count, dtype: int64},
 'Merchant_Category': {'n_unqiue': 5,
  'value_counts': Merchant_Category
  Clothing       8071
  Restaurants    8002
  Electronics    8000
  Travel         7981
  Groceries      7946
  Name: count, dtype: int64},
 'Card_Type': {'n_unqiue': 4,
  'value_counts': Card_Type
  Mastercard    10149
  Visa          10002
  Amex           9968
  Discover       9881
  Name: count, dtype: int64},
 'Authentication_Method': {'n_unqiue': 4,
  'value_counts': Authentication_Method
  PIN          10052
  Biometric    10052
  Password      9955
  OTP           9941
  Name: count, dtype: int64}}

In [21]:
### all the columns are balanced, so we can apply the batch one hot, we don't have to fix any column
cat_train_processed = one_hot(cat_cols_train)
cat_train_processed.head()

,Transaction_Type_Bank Transfer_1,Transaction_Type_Online_1,Transaction_Type_POS_1,Device_Type_Mobile_1,Device_Type_Tablet_1,Location_Mumbai_1,Location_New York_1,Location_Sydney_1,Location_Tokyo_1,Merchant_Category_Electronics_1,Merchant_Category_Groceries_1,Merchant_Category_Restaurants_1,Merchant_Category_Travel_1,Card_Type_Discover_1,Card_Type_Mastercard_1,Card_Type_Visa_1,Authentication_Method_OTP_1,Authentication_Method_PIN_1,Authentication_Method_Password_1
0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0
1,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,1,0,0
2,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0,0
3,0,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0
4,0,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1

In [32]:
### the original dataset
cat_cols_train.head()

,Transaction_Type,Device_Type,Location,Merchant_Category,Card_Type,Authentication_Method
0,ATM Withdrawal,Tablet,London,Travel,Mastercard,PIN
1,Bank Transfer,Mobile,New York,Electronics,Visa,OTP
2,ATM Withdrawal,Tablet,Sydney,Electronics,Mastercard,OTP
3,Online,Mobile,London,Travel,Discover,PIN
4,Online,Mobile,Sydney,Groceries,Amex,Password

In [22]:
### checking the shape
get_shape(cat_train_processed)

(40000, 19)

##### *************** Valid data *****************

In [29]:
### loading the data
cat_cols_valid = load_data(cat_cols_valid_path)
cat_cols_valid.head()

,Transaction_Type,Device_Type,Location,Merchant_Category,Card_Type,Authentication_Method
0,Online,Mobile,Sydney,Clothing,Mastercard,OTP
1,Bank Transfer,Mobile,New York,Travel,Amex,Password
2,ATM Withdrawal,Laptop,Tokyo,Restaurants,Amex,Password
3,POS,Tablet,Mumbai,Travel,Mastercard,OTP
4,Bank Transfer,Tablet,Sydney,Groceries,Visa,Biometric

In [13]:
### get shape
get_shape(cat_cols_valid)

(10000, 6)

In [14]:
### checking the nan values
get_nan(cat_cols_valid)

Transaction_Type         0
Device_Type              0
Location                 0
Merchant_Category        0
Card_Type                0
Authentication_Method    0
dtype: int64

In [15]:
### all the features needs the one hot encoding
### there is no label based categorical feature

In [16]:
### checking the summary of the columns
cat_summary(cat_cols_valid)

{'Transaction_Type': {'n_unqiue': 4,
  'value_counts': Transaction_Type
  Bank Transfer     2535
  ATM Withdrawal    2532
  Online            2516
  POS               2417
  Name: count, dtype: int64},
 'Device_Type': {'n_unqiue': 3,
  'value_counts': Device_Type
  Tablet    3375
  Laptop    3325
  Mobile    3300
  Name: count, dtype: int64},
 'Location': {'n_unqiue': 5,
  'value_counts': Location
  Tokyo       2055
  Mumbai      2016
  London      1999
  Sydney      1973
  New York    1957
  Name: count, dtype: int64},
 'Merchant_Category': {'n_unqiue': 5,
  'value_counts': Merchant_Category
  Groceries      2073
  Travel         2034
  Restaurants    1974
  Clothing       1962
  Electronics    1957
  Name: count, dtype: int64},
 'Card_Type': {'n_unqiue': 4,
  'value_counts': Card_Type
  Visa          2558
  Mastercard    2544
  Amex          2451
  Discover      2447
  Name: count, dtype: int64},
 'Authentication_Method': {'n_unqiue': 4,
  'value_counts': Authentication_Method
  Biometric    2539
  PIN          2534
  Password     2502
  OTP          2425
  Name: count, dtype: int64}}

In [23]:
### applying the one hot encoding at once
cat_valid_processed = one_hot(cat_cols_valid)
cat_valid_processed.head()

,Transaction_Type_Bank Transfer_1,Transaction_Type_Online_1,Transaction_Type_POS_1,Device_Type_Mobile_1,Device_Type_Tablet_1,Location_Mumbai_1,Location_New York_1,Location_Sydney_1,Location_Tokyo_1,Merchant_Category_Electronics_1,Merchant_Category_Groceries_1,Merchant_Category_Restaurants_1,Merchant_Category_Travel_1,Card_Type_Discover_1,Card_Type_Mastercard_1,Card_Type_Visa_1,Authentication_Method_OTP_1,Authentication_Method_PIN_1,Authentication_Method_Password_1
0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0
1,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1
3,0,0,1,0,1,1,0,0,0,0,0,0,1,0,1,0,1,0,0
4,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0

In [30]:
### the original dataset
cat_cols_valid.head()

,Transaction_Type,Device_Type,Location,Merchant_Category,Card_Type,Authentication_Method
0,Online,Mobile,Sydney,Clothing,Mastercard,OTP
1,Bank Transfer,Mobile,New York,Travel,Amex,Password
2,ATM Withdrawal,Laptop,Tokyo,Restaurants,Amex,Password
3,POS,Tablet,Mumbai,Travel,Mastercard,OTP
4,Bank Transfer,Tablet,Sydney,Groceries,Visa,Biometric

In [24]:
### veryfying the shape
get_shape(cat_valid_processed)

(10000, 19)

##### *********** saving the data **************

In [19]:
### setting up the paths
cat_train_processed_path = '../data/intermidiate/cat_train_processed'
cat_valid_processed_path = '../data/intermidiate/cat_valid_processed'

In [25]:
### saving up the data
save_data(cat_train_processed, cat_train_processed_path)
save_data(cat_valid_processed, cat_valid_processed_path)

In [26]:
### veryfying the saving of the files
cat_train_processed = load_data(cat_train_processed_path)
cat_train_processed.head()

,Transaction_Type_Bank Transfer_1,Transaction_Type_Online_1,Transaction_Type_POS_1,Device_Type_Mobile_1,Device_Type_Tablet_1,Location_Mumbai_1,Location_New York_1,Location_Sydney_1,Location_Tokyo_1,Merchant_Category_Electronics_1,Merchant_Category_Groceries_1,Merchant_Category_Restaurants_1,Merchant_Category_Travel_1,Card_Type_Discover_1,Card_Type_Mastercard_1,Card_Type_Visa_1,Authentication_Method_OTP_1,Authentication_Method_PIN_1,Authentication_Method_Password_1
0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0
1,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,1,0,0
2,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0,0
3,0,1,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0
4,0,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1

In [27]:
### cat_valid_processed
cat_valid_processed = load_data(cat_valid_processed_path)
cat_valid_processed.head()

,Transaction_Type_Bank Transfer_1,Transaction_Type_Online_1,Transaction_Type_POS_1,Device_Type_Mobile_1,Device_Type_Tablet_1,Location_Mumbai_1,Location_New York_1,Location_Sydney_1,Location_Tokyo_1,Merchant_Category_Electronics_1,Merchant_Category_Groceries_1,Merchant_Category_Restaurants_1,Merchant_Category_Travel_1,Card_Type_Discover_1,Card_Type_Mastercard_1,Card_Type_Visa_1,Authentication_Method_OTP_1,Authentication_Method_PIN_1,Authentication_Method_Password_1
0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0
1,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1
3,0,0,1,0,1,1,0,0,0,0,0,0,1,0,1,0,1,0,0
4,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0